name: azkark
description: An azkar app for muslim.

version: 1.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.1.0
  screenshot: ^1.2.3
  image_gallery_saver: '^1.7.1'
  permission_handler:
  share_plus: ^4.0.10+1
  flutter_local_notifications: ^9.9.0
  timezone: ^0.8.0
  android_alarm_manager_plus: ^2.0.6+1
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.0.1
  quran: ^1.1.2
  backdrop: ^0.8.1
  google_fonts: ^3.0.1
  http:
  geolocator:
  audioplayers: ^1.0.1
  assets_audio_player: ^3.0.5
  file_picker: ^5.0.1
  intl: ^0.17.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/database.db
   - assets/images/background/
   - assets/images/sections/
   - assets/images/icons/asmaallah/
   - assets/images/icons/not_fount/
   - assets/images/icons/prayer/
   - assets/images/icons/favorites/
   - assets/images/icons/sebha/
   - assets/images/icons/quran/
   - assets/lang/
   - assets/surah.json
   - assets/fonts/
   - assets/azan/


  fonts:
    - family: '0'
      fonts:
        - asset: assets/fonts/RB/RB-Regular.ttf
        - asset: assets/fonts/RB/RB-Bold.ttf
    
    - family: '1'
      fonts:
        - asset: assets/fonts/Janna/Janna-Regular.ttf
        - asset: assets/fonts/Janna/Janna-Bold.ttf
    
    - family: '2'
      fonts:
        - asset: assets/fonts/Al-Quran/Al-Quran-Regular.ttf
        - asset: assets/fonts/Al-Quran/Al-Quran-Bold.ttf

    - family: '3'
      fonts:
        - asset: assets/fonts/Uthman-Taha-Naskh/Uthman-Taha-Naskh-Regular.otf
        - asset: assets/fonts/Uthman-Taha-Naskh/Uthman-Taha-Naskh-Bold.otf
    
    - family: '4'
      fonts:
        - asset: assets/fonts/DroidArabic.otf
    
    - family: '5'
      fonts:
        - asset: assets/fonts/JF.otf
    
    - family: '6'
      fonts:
        - asset: assets/fonts/noorehuda.ttf
    
    - family: '7'
      fonts:
        - asset: assets/fonts/noorehira.ttf
    
    - family: '8'
      fonts:
        - asset: assets/fonts/Ruqaa.ttf

    - family: Aldhabi
      fonts:
        - asset: assets/fonts/Al-Quran/aldhabi.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Al-Quran/Amiri-Bold.ttf
        - asset: assets/fonts/Al-Quran/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Al-Quran/Amiri-Regular.ttf
        - asset: assets/fonts/Al-Quran/Amiri-Italic.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/Al-Quran/NotoNastaliqUrdu-Bold.ttf
        - asset: assets/fonts/Al-Quran/NotoNastaliqUrdu-Regular.ttf

